services:
  app:
    image: ghcr.io/excoffierleonard/downdetector:latest
    build:
      context: .
    environment:
      WEBHOOK_URL: ${WEBHOOK_URL}
      DISCORD_ID: ${DISCORD_ID}
    volumes:
      - config:/.config/downdetector

volumes:
  config: {}