name: Deploy

permissions:
  contents: read

on:
  workflow_run:
    workflows: ["Publish"]
    types:
      - completed
    branches:
      - main

jobs:
  deploy-docker:
    name: Deploy Docker image to production server
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v4

      - name: Create Docker context
        uses: amirmarmul/docker-context-ssh-action@v1
        with:
          ssh-host: ${{ secrets.PROD_HOST }}
          ssh-username: ${{ secrets.PROD_USERNAME }}
          ssh-private-key: ${{ secrets.PROD_SSH_KEY }}

      - name: Redeploy Docker image over Docker context
        env:
          WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
          DISCORD_ID: ${{ secrets.DISCORD_ID }}  
        run: docker --context remote compose pull && \
             docker --context remote compose down && \
             docker --context remote compose up -d